/**
* Mini OEMS API
* Minimal Order / Execution Management System HTTP API (v1). This specification is the single source of truth — server and client code is generated from it via openapi-generator. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Fill.h
 *
 * 
 */

#ifndef Fill_H_
#define Fill_H_


#include "Side.hpp"
#include "oatpp/core/macro/codegen.hpp"
#include "oatpp/core/Types.hpp"

namespace org::openapitools::server::model
{

/* Begin DTO code-generation */
#include OATPP_CODEGEN_BEGIN(DTO)

/**
 * Message Data-Transfer-Object
 */
class Fill : public oatpp::DTO {

  DTO_INIT(Fill, DTO /* Extends */)

  DTO_FIELD(oatpp::Int64, execution_id);

  DTO_FIELD(oatpp::String, symbol);

  DTO_FIELD(oatpp::Int64, aggressive_order_id);

  DTO_FIELD(oatpp::Int64, passive_order_id);

  DTO_FIELD(org::openapitools::server::model::Side, side);

  DTO_FIELD(oatpp::Int64, price);

  DTO_FIELD(oatpp::Int64, quantity);


};

/* End DTO code-generation */
#include OATPP_CODEGEN_END(DTO)


} // namespace org::openapitools::server::model

#endif /* Fill_H_ */
