/**
* Mini OEMS API
* Minimal Order / Execution Management System HTTP API (v1). This specification is the single source of truth — server and client code is generated from it via openapi-generator. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Health.h
 *
 * 
 */

#ifndef Health_H_
#define Health_H_


#include "oatpp/core/macro/codegen.hpp"
#include "oatpp/core/Types.hpp"

namespace org::openapitools::server::model
{

/* Begin DTO code-generation */
#include OATPP_CODEGEN_BEGIN(DTO)

/**
 * Message Data-Transfer-Object
 */
class Health : public oatpp::DTO {

  DTO_INIT(Health, DTO /* Extends */)

  DTO_FIELD(oatpp::String, status);


};

/* End DTO code-generation */
#include OATPP_CODEGEN_END(DTO)


} // namespace org::openapitools::server::model

#endif /* Health_H_ */
