/**
* Mini OEMS API
* Minimal Order / Execution Management System HTTP API (v1). This specification is the single source of truth — server and client code is generated from it via openapi-generator. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NewOrderRequest.h
 *
 * 
 */

#ifndef NewOrderRequest_H_
#define NewOrderRequest_H_


#include "oatpp/core/macro/codegen.hpp"
#include "oatpp/core/Types.hpp"

namespace org::openapitools::server::model
{

/* Begin DTO code-generation */
#include OATPP_CODEGEN_BEGIN(DTO)

/**
 * Message Data-Transfer-Object
 */
class NewOrderRequest : public oatpp::DTO {

  DTO_INIT(NewOrderRequest, DTO /* Extends */)

  DTO_FIELD(oatpp::String, client_order_id);
  DTO_FIELD(oatpp::Boolean, client_order_idIsSet);
  DTO_FIELD(oatpp::String, symbol);

  DTO_FIELD(oatpp::String, side);

  DTO_FIELD(oatpp::String, type);

  DTO_FIELD(oatpp::Int64, price);
  DTO_FIELD(oatpp::Boolean, priceIsSet);
  DTO_FIELD(oatpp::Int64, quantity);


};

/* End DTO code-generation */
#include OATPP_CODEGEN_END(DTO)


} // namespace org::openapitools::server::model

#endif /* NewOrderRequest_H_ */
