/**
* Mini OEMS API
* Minimal Order / Execution Management System HTTP API (v1). This specification is the single source of truth — server and client code is generated from it via openapi-generator. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * OrderStatus.h
 *
 * 
 */

#ifndef OrderStatus_H_
#define OrderStatus_H_


#include "oatpp/core/Types.hpp"

namespace org::openapitools::server::model
{


typedef oatpp::String OrderStatus;
class OrderStatusValues {
public:
  static OrderStatus PendingNew(void) { return "PendingNew"; }
  static OrderStatus Accepted(void) { return "Accepted"; }
  static OrderStatus PartiallyFilled(void) { return "PartiallyFilled"; }
  static OrderStatus Filled(void) { return "Filled"; }
  static OrderStatus PendingCancel(void) { return "PendingCancel"; }
  static OrderStatus Cancelled(void) { return "Cancelled"; }
  static OrderStatus Rejected(void) { return "Rejected"; }
};

} // namespace org::openapitools::server::model

#endif /* OrderStatus_H_ */
