/**
* Mini OEMS API
* Minimal Order / Execution Management System HTTP API (v1). This specification is the single source of truth — server and client code is generated from it via openapi-generator. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Order.h
 *
 * 
 */

#ifndef Order_H_
#define Order_H_


#include "Side.hpp"
#include "OrderStatus.hpp"
#include "OrderType.hpp"
#include "oatpp/core/macro/codegen.hpp"
#include "oatpp/core/Types.hpp"

namespace org::openapitools::server::model
{

/* Begin DTO code-generation */
#include OATPP_CODEGEN_BEGIN(DTO)

/**
 * Message Data-Transfer-Object
 */
class Order : public oatpp::DTO {

  DTO_INIT(Order, DTO /* Extends */)

  DTO_FIELD(oatpp::Int64, internal_id);

  DTO_FIELD(oatpp::String, client_order_id);

  DTO_FIELD(oatpp::String, symbol);

  DTO_FIELD(org::openapitools::server::model::Side, side);

  DTO_FIELD(org::openapitools::server::model::OrderType, type);

  DTO_FIELD(oatpp::Int64, price);

  DTO_FIELD(oatpp::Int64, order_qty);

  DTO_FIELD(oatpp::Int64, filled_qty);

  DTO_FIELD(oatpp::Int64, remaining_qty);

  DTO_FIELD(org::openapitools::server::model::OrderStatus, status);


};

/* End DTO code-generation */
#include OATPP_CODEGEN_END(DTO)


} // namespace org::openapitools::server::model

#endif /* Order_H_ */
