/**
* Mini OEMS API
* Minimal Order / Execution Management System HTTP API (v1). This specification is the single source of truth — server and client code is generated from it via openapi-generator. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * OrderType.h
 *
 * 
 */

#ifndef OrderType_H_
#define OrderType_H_


#include "oatpp/core/Types.hpp"

namespace org::openapitools::server::model
{


typedef oatpp::String OrderType;
class OrderTypeValues {
public:
  static OrderType Limit(void) { return "Limit"; }
  static OrderType Market(void) { return "Market"; }
};

} // namespace org::openapitools::server::model

#endif /* OrderType_H_ */
