/**
* Mini OEMS API
* Minimal Order / Execution Management System HTTP API (v1). This specification is the single source of truth — server and client code is generated from it via openapi-generator. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Side.h
 *
 * 
 */

#ifndef Side_H_
#define Side_H_


#include "oatpp/core/Types.hpp"

namespace org::openapitools::server::model
{


typedef oatpp::String Side;
class SideValues {
public:
  static Side Buy(void) { return "Buy"; }
  static Side Sell(void) { return "Sell"; }
};

} // namespace org::openapitools::server::model

#endif /* Side_H_ */
