/**
* Mini OEMS API
* Minimal Order / Execution Management System HTTP API (v1). This specification is the single source of truth — server and client code is generated from it via openapi-generator. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * BooksApi.h
 *
 * 
 */

#ifndef BooksApi_H_
#define BooksApi_H_



#include "oatpp/web/server/api/ApiController.hpp"
#include "oatpp/core/macro/codegen.hpp"
#include "oatpp/core/macro/component.hpp"
#include "oatpp/core/Types.hpp"

#include "ApiError.hpp"
#include "Book.hpp"

#include OATPP_CODEGEN_BEGIN(ApiController) ///< Begin ApiController codegen section

namespace org::openapitools::server::api
{

class BooksApi : public oatpp::web::server::api::ApiController {
public:

  BooksApi(OATPP_COMPONENT(std::shared_ptr<ObjectMapper>, objectMapper) /* Inject object mapper */)
    : oatpp::web::server::api::ApiController(objectMapper) 
  {}

  /// <summary>
  /// Get the current order book snapshot for a symbol
  /// </summary>
  /// <remarks>
  /// 
  /// </remarks>
  /// <param name="request">HTTP Request</param>
  /// <param name="symbol"></param>
  virtual std::shared_ptr<oatpp::web::protocol::http::outgoing::Response> get_book(const std::shared_ptr<IncomingRequest> &request, const oatpp::String &symbol) = 0;

  ENDPOINT("GET", "/v1/books/{symbol}", get_book_handler, REQUEST(std::shared_ptr<IncomingRequest>, request), PATH(oatpp::String, symbol)) {
      return get_book(request, symbol);
  }
};

#include OATPP_CODEGEN_END(ApiController) ///< End ApiController codegen section

} // namespace org::openapitools::server::api

#endif /* BooksApi_H_ */

