/**
* Mini OEMS API
* Minimal Order / Execution Management System HTTP API (v1). This specification is the single source of truth — server and client code is generated from it via openapi-generator. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ExecutionsApi.h
 *
 * 
 */

#ifndef ExecutionsApi_H_
#define ExecutionsApi_H_



#include "oatpp/web/server/api/ApiController.hpp"
#include "oatpp/core/macro/codegen.hpp"
#include "oatpp/core/macro/component.hpp"
#include "oatpp/core/Types.hpp"

#include "Fill.hpp"

#include OATPP_CODEGEN_BEGIN(ApiController) ///< Begin ApiController codegen section

namespace org::openapitools::server::api
{

class ExecutionsApi : public oatpp::web::server::api::ApiController {
public:

  ExecutionsApi(OATPP_COMPONENT(std::shared_ptr<ObjectMapper>, objectMapper) /* Inject object mapper */)
    : oatpp::web::server::api::ApiController(objectMapper) 
  {}

  /// <summary>
  /// List all executed fills
  /// </summary>
  /// <remarks>
  /// 
  /// </remarks>
  /// <param name="request">HTTP Request</param>
  virtual std::shared_ptr<oatpp::web::protocol::http::outgoing::Response> list_executions(const std::shared_ptr<IncomingRequest> &request) = 0;

  ENDPOINT("GET", "/v1/executions", list_executions_handler, REQUEST(std::shared_ptr<IncomingRequest>, request)) {
      return list_executions(request);
  }
};

#include OATPP_CODEGEN_END(ApiController) ///< End ApiController codegen section

} // namespace org::openapitools::server::api

#endif /* ExecutionsApi_H_ */

