/**
* Mini OEMS API
* Minimal Order / Execution Management System HTTP API (v1). This specification is the single source of truth — server and client code is generated from it via openapi-generator. 
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * OrdersApi.h
 *
 * 
 */

#ifndef OrdersApi_H_
#define OrdersApi_H_



#include "oatpp/web/server/api/ApiController.hpp"
#include "oatpp/core/macro/codegen.hpp"
#include "oatpp/core/macro/component.hpp"
#include "oatpp/core/Types.hpp"

#include "ApiError.hpp"
#include "NewOrderRequest.hpp"
#include "Order.hpp"
#include "OrderStatus.hpp"

#include OATPP_CODEGEN_BEGIN(ApiController) ///< Begin ApiController codegen section

namespace org::openapitools::server::api
{

class OrdersApi : public oatpp::web::server::api::ApiController {
public:

  OrdersApi(OATPP_COMPONENT(std::shared_ptr<ObjectMapper>, objectMapper) /* Inject object mapper */)
    : oatpp::web::server::api::ApiController(objectMapper) 
  {}

  /// <summary>
  /// Cancel a resting order
  /// </summary>
  /// <remarks>
  /// 
  /// </remarks>
  /// <param name="request">HTTP Request</param>
  /// <param name="id"></param>
  virtual std::shared_ptr<oatpp::web::protocol::http::outgoing::Response> cancel_order(const std::shared_ptr<IncomingRequest> &request, const oatpp::Int64 &id) = 0;

  ENDPOINT("POST", "/v1/orders/{id}/cancel", cancel_order_handler, REQUEST(std::shared_ptr<IncomingRequest>, request), PATH(oatpp::Int64, id)) {
      return cancel_order(request, id);
  }
  /// <summary>
  /// Fetch a single order by internal id
  /// </summary>
  /// <remarks>
  /// 
  /// </remarks>
  /// <param name="request">HTTP Request</param>
  /// <param name="id"></param>
  virtual std::shared_ptr<oatpp::web::protocol::http::outgoing::Response> get_order(const std::shared_ptr<IncomingRequest> &request, const oatpp::Int64 &id) = 0;

  ENDPOINT("GET", "/v1/orders/{id}", get_order_handler, REQUEST(std::shared_ptr<IncomingRequest>, request), PATH(oatpp::Int64, id)) {
      return get_order(request, id);
  }
  /// <summary>
  /// List orders, optionally filtered
  /// </summary>
  /// <remarks>
  /// 
  /// </remarks>
  /// <param name="request">HTTP Request</param>
  /// <param name="symbol"> (optional, default to &quot;&quot;)</param>
  /// <param name="status"> (optional, default to std::make_shared&lt;OrderStatus&gt;())</param>
  virtual std::shared_ptr<oatpp::web::protocol::http::outgoing::Response> list_orders(const std::shared_ptr<IncomingRequest> &request, const oatpp::String &symbol, const org::openapitools::server::model::OrderStatus &status) = 0;

  ENDPOINT("GET", "/v1/orders", list_orders_handler, REQUEST(std::shared_ptr<IncomingRequest>, request), QUERY(oatpp::String, symbol), QUERY(org::openapitools::server::model::OrderStatus, status)) {
      return list_orders(request, symbol, status);
  }
  /// <summary>
  /// Submit a new order
  /// </summary>
  /// <remarks>
  /// 
  /// </remarks>
  /// <param name="request">HTTP Request</param>
  /// <param name="newOrderRequest"></param>
  virtual std::shared_ptr<oatpp::web::protocol::http::outgoing::Response> submit_order(const std::shared_ptr<IncomingRequest> &request, const oatpp::Object<org::openapitools::server::model::NewOrderRequest> &newOrderRequest) = 0;

  ENDPOINT("POST", "/v1/orders", submit_order_handler, REQUEST(std::shared_ptr<IncomingRequest>, request), BODY_DTO(oatpp::Object<org::openapitools::server::model::NewOrderRequest>, newOrderRequest)) {
      return submit_order(request, newOrderRequest);
  }
};

#include OATPP_CODEGEN_END(ApiController) ///< End ApiController codegen section

} // namespace org::openapitools::server::api

#endif /* OrdersApi_H_ */

